version: "3"
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - DEFAULT_REGION=sa-east-1
      - SERVICES=secretsmanager
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  aws_cli:
    image: amazon/aws-cli
    depends_on: 
      - localstack
    entrypoint: /bin/sh -c
    command: >  
     '
     RED="\033[0;31m"
     GREEN="\033[0;32m"
     ACCESS_KEY="default"
     SECRET_KEY="default"
     REGION="sa-east-1"
     COUNTER=15;
     SM_DESIRED_STATE="secretsmanager available";
     SERVICE_ACTUAL_STATE=0;
     
      while [ $$COUNTER -ne 0 ] && [ $$SERVICE_ACTUAL_STATE != 1 ]
      
      do 
      RESPONSE=$$(curl -sb --connect-timeout 2 /dev/null "localstack:4566/health?redirect" | tr -cd [^[:alnum:][:space:]]+) 
      echo " Response from Localstack $$RESPONSE";

      if [[ $$RESPONSE == *"$$SM_DESIRED_STATE"* ]]; then SERVICE_ACTUAL_STATE=1; else SERVICE_ACTUAL_STATE=0; fi;
     
     echo $$SERVICE_ACTUAL_STATE
      COUNTER=$$((COUNTER-1)); 
      echo "Service is not ready yet! $$COUNTER retries left."; 
      sleep 3; 
      done; 
      echo backend is up;

      echo "########### Creating profile ###########"

      aws configure set aws_access_key_id $$ACCESS_KEY --profile=localstack
      aws configure set aws_secret_access_key $$SECRET_KEY --profile=localstack      
      aws configure set region $$REGION --profile=localstack

      echo "########### Listing profile ###########"
      aws configure list --profile=localstack

      echo "########### Creating SM ###########"
      aws --endpoint http://localstack:4566 --profile localstack secretsmanager create-secret --name /secret/bff-api-1 --description "Segredos para acesso a API" --secret-string "{\"ts\":\"1\",\"apiKey\":\"f59dbe01285f1d360542b5c47a9516e3\",\"hash\":\"0ea6be79e04ac1b0400d65ffc11088f9\"}"
      aws --endpoint http://localstack:4566 --profile localstack secretsmanager create-secret --name /secret/bff-api-2 --description "Segredos para acesso a API" --secret-string "{\"ts\":\"1\",\"apiKey\":\"fffffffffffffffffffffffffffffffff\",\"hash\":\"fffffffffffffffffffffffffffffff\"}"
      echo -e "$${GREEN}########### [Success] Secrets Manager created ###########"
      
      '